#!/bin/sh -e

# SPDX-License-Identifier: MIT

. $SLAB_ROOT/tools/utils/misc.sh

#######################################################################
# Options

confdir=$SLAB_ROOT/tools/lfmmi/conf
use_gpu=false
njobs=4

#######################################################################

show_usage() {
    echo "usage: $(basename $0) [options] <lang-dir> <train-dataset-dir> <dev-dataset-dir> <model> <out-dir>" #<fea-dir> <configname>"
}

show_help() {
    show_usage
    echo ""
    echo "Training a neural network using LF-MMI."
    echo ""
    echo "  --confdir       directory where to find the config files (default: $confdir)"
    echo "  --use-gpu        use a GPU to train the model (default: $use_gpu)"
    echo "  --help -h       show this help message"
    echo "  --njobs         number of parallel jobs (default: $njobs)"
}

. $SLAB_ROOT/tools/utils/parse_options.sh

if [ $# -ne 5 ]; then
    show_usage 1>&2
    exit 1
fi

langdir=$1
traindir=$2
devdir=$3
inmodel=$4
odir=$5

echo "--> Build the HMM components for each basic units."
slab_monophone_mkhmms \
    $confdir/hmm_speechunit.toml \
    $confdir/hmm_nonspeechunit.toml \
    $langdir/units \
    $odir/hmms.jld2

echo "--> Build the pronunciation fsms."
slab_monophone_mklexicon \
    $langdir/lexicon \
    $odir/lexicon.fsms.jld2

echo "--> Compile the numerator fsms (train set)."
slab_monophone_mkalis \
    --njobs $njobs \
    $odir/hmms.jld2 \
    $odir/lexicon.fsms.jld2 \
    $traindir/trans \
    $odir/train_numerator_fsms.jld2

echo "--> Compile the numerator fsms (dev set)."
slab_monophone_mkalis \
    --njobs $njobs \
    $odir/hmms.jld2 \
    $odir/lexicon.fsms.jld2 \
    $devdir/trans \
    $odir/dev_numerator_fsms.jld2

echo "--> Compile the denominator fsm."
slab_monophone_mkploop \
    --start-sil true  \
    --end-sil true \
    $odir/hmms.jld2 \
    $odir/denominator_fsm.jld2


# Final step is to train the model.
# julia scripts/train.jl
