# SPDX-License-Identifier: MIT

# Global configuration. We recommend that the following directories
# to be set on hard drive with large memory as they will be served to
# store features and other data.

ROOT ?= ~/SpeechRecipes
DATASETS ?= ~/Datasets
ROOT_FEA_DIR ?= ~/Features

JULIA ?= julia --project=$(ROOT)

CONFIGS ?= $(ROOT)/configs
SCRIPTS ?= $(ROOT)/scripts
