#!/bin/sh -e

. $SLAB_ROOT/utils/misc.sh

#######################################################################
# Options

sil_sym="<SIL>"
oov_sym="<UNK>"
between_silprob=0.1
edge_silprob=0.8

#######################################################################

show_usage() {
    echo "usage: $(basename $0) modelfile modelconfig trainfea hmms model"
}

show_help() {
    show_usage
    echo ""
    echo "Create and initialize a neural network. 'modelfile' is a Julia"
    echo "file implementing the construction of the model."
    echo ""
}

. $SLAB_ROOT/utils/parse_options.sh

if [ $# -ne 5 ]; then
    show_usage 1>&2
    exit 1
fi

modelfile=$1 && assert_not_missing
modelconfig=$2 && assert_not_missing
trainfea=$3 && assert_not_missing
hmms=$4 && assert_not_missing
model=$5

if [ ! -f $model ]; then
    julia --project $SLAB_ROOT/steps/lfmmi/scripts/mkmodel.jl \
        $modelfile \
        $modelconfig \
        $trainfea \
        $hmms \
        $model
else
    echo "Model already created in $model"
fi

