#!/bin/sh -e

# SPDX-License-Identifier: MIT

. $SLAB_ROOT/utils/misc.sh

show_usage() {
    echo "usage: $(basename $0) <topo> <units> <out-hmms>"
}

show_help() {
    show_usage
    echo ""
    echo "Build a set of HMMs for the units in <unit> based on the"
    echo "topology file <topo>."
    echo ""
    echo "  -h, --help      show this help message"
}

. $SLAB_ROOT/utils/parse_options.sh

if [ $# -ne 3 ]; then
    show_usage 1>&2
    exit 1
fi

topo=$1 && assert_not_missing $su_config
units=$2
hmms=$3

if [ -f $hmms ]; then
    echo "The hmms are already built in $hmms."
    exit 0
fi

julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/steps/hmm/scripts/makehmms.jl $topo $units $hmms

