#!/bin/sh

# We don't use the -e option on purpose as it causes issues with grep.

# SPDX-License-Identifier: MIT

. $SLAB_ROOT/tools/utils/utils.sh

show_usage() {
    echo "usage: $(basename $0) [options] [dataset]"
}

show_help() {
    show_usage
    echo ""
    echo "Show the possible type of GMMs. If 'dataset' is provided, show "
    echo "the type of GMMs already trained for this dataset."
    echo ""
    echo "  -h              show this help message"
}

while :; do
    case "$1" in
        -h) show_help; exit 0;;
        -*)
            echo "Unknown option: $1. Try '$0 -h' for more informations."  1>&2
            echo "" 1>&2
            show_usage 1>&2
            exit 1;;
        *) break;;
    esac
    shift
done

if [ $# -gt 1 ]; then
    show_usage 1>&2
    exit 1
fi

dataset=$1

tmpf=$(mktemp)
trap 'rm "$tmpf"; trap - EXIT; exit' EXIT INT HUP

for file in $SLAB_ROOT/tools/gmm/conf/*toml; do
    bname=$(basename $file)
    echo ${bname%%.*} >> $tmpf
done

mdls=$(ls $SLAB_MODELS/$dataset | grep -f $tmpf)

if [ -z $dataset ]; then
    cat $tmpf
elif [ -d $SLAB_MODELS/$dataset ] && [ ! -z $mdls ]; then
    for file in $(ls $SLAB_MODELS/$dataset/*/final.jld2); do
        basename $(dirname $file)
    done
else
    echo "No GMM trained for $dataset."
fi

