
dataset = "mini_librispeech"
expdir = "exp3"
datasetsdir = "/people/ondel/Datasets"

[features]
dir = "/people/ondel/Features"
name = "kaldi_mfcc_hires_16kHz"

[graphs]
hmm_topologies = "conf/topo_unit2.toml"
ngram_order = 3
sil_sym = "<SIL>"
oov_sym = "<UNK>"
between_silprob = 0.2
edge_silprob = 0.8

[model]
dropout = 0.2
dilations = [  1,   1,   3,   3,   3]
kernel-sizes = [  3,   3,   3,   3,   3]
hidden-dims = [384, 384, 384, 384, 384]
strides = [  1,   1,   1,   1,   3]

[training]
epochs = 40
curriculum = 1  # number of epoch of "curriculum training".
minibatch_size = 100

[training.scheduler]
factor = 0.5
patience = 1
threshold = 1e-4
min_learning_rate = 1e-5

[training.optimizer]
learning_rate = 1e-3
beta1 = 0.9
beta2 = 0.999
