
[dataset]
dir = "/people/ondel/Datasets"
name = "wsj"

[experiment]
dir = "exp"

[features]
dir = "/people/ondel/Features"
name = "kaldi_mfcc_hires_16kHz"

[graphs]
dir = "graphs_test"
hmm_topologies = "topo_unit.toml"
ngram_order = 3
sil_sym = "<SIL>"
oov_sym = "<UNK>"
between_silprob = 0.2
edge_silprob = 0.8
sample = true

[model]
dropout = 0.2
dilations = [  1,   1,   3,   3,   3]
kernel-sizes = [  3,   3,   3,   3,   3]
hidden-dims = [384, 384, 384, 384, 384]
strides = [  1,   1,   1,   1,   3]

[training]
dir = "train"
epochs = 20
curriculum = 1
minibatch_size = 100
update_freq = 1
use_gpu = true

[training.scheduler]
factor = 0.5
patience = 1
threshold = 1e-4
min_learning_rate = 1e-5

[training.optimizer]
learning_rate = 1e-3
beta1 = 0.9
beta2 = 0.999

[output]
dir = "output"
