#!/bin/sh -e

# SPDX-License-Identifier: MIT

. $SLAB_ROOT/tools/utils/misc.sh

#######################################################################
# Options

start_sil=false
end_sil=false

#######################################################################

show_usage() {
    echo "usage: $(basename 0) [options] <hmms> <ploop>"
}

show_help() {
    show_usage
    echo ""
    echo "Make phone-loop decoding graph."
    echo ""
    echo "  --end-sil       phone-loop ends with a non-speech unit (default: $end_sil)"
    echo "  --help -h       show this help message"
    echo "  --start-sil     phone-loop starts with a non-speech unit (default: $start_sil)"
}

. $SLAB_ROOT/tools/utils/parse_options.sh

if [ $# -ne 2 ]; then
    show_usage 1>&2
    exit 1
fi

hmms=$1 && assert_not_missing $hmms
ploop=$2

if [ -f $ploop ]; then
    echo "The phone-loop already exists in $ploop."
    exit 0
fi

[ $start_sil=yes ] && sopt="-s"
[ $end_sil=yes ] && eopt="-e"

julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/monophone/scripts/makephoneloop.jl \
    $sopt $eopt \
    $hmms \
    $ploop

