#!/bin/sh -e

# SPDX-License-Identifier: MIT

. $SLAB_ROOT/tools/utils/misc.sh

show_usage() {
    echo "usage: $(basename $0) [options] <in-lexicon> <out-lexiconfsms>"
}

show_help() {
    show_usage
    echo ""
    echo "Make lexicon fsms (one per word) from a lexicon file."
    echo ""
    echo "  --help -h       show this help message"
}

. $SLAB_ROOT/tools/utils/parse_options.sh

if [ $# -ne 2 ]; then
    show_usage 1>&2
    exit 1
fi

inlexicon=$1 && assert_not_missing $inlexicon
outlexicon=$2

if [ -f $outlexicon ]; then
    echo "The lexicon fsms are already built in $outlexicon."
    exit 0
fi

julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/monophone/scripts/makelexicon.jl \
    $inlexicon \
    $outlexicon

