# SPDX-License-Identifier: MIT

include ../../Makefile.config

# Feature type
FEA_TYPE ?= mfcc_d_dd_16kHz

# Input features directory
FEA_DIR ?= $(ROOT_FEA_DIR)/$(DATASET)/$(FEA_TYPE)

# Output directory
GMM_DIR ?= $(shell pwd)/$(DATASET)/$(FEA_TYPE)

# Number of utterance to use for computing the global statistics (for
# initialization)
GMM_NUTTS ?= 10000

# Options for the training
GMM_TRAIN_OPTS ?= --use-gpu --single-precision
