#!/bin/sh -e

# SPDX-License-Identifier: MIT

. $SLAB_ROOT/tools/utils/misc.sh

#######################################################################
# Options

njobs=1
logdir=$PWD

#######################################################################

show_usage() {
    echo "usage: $(basename $0) [options] <hmms> <lexicon> <trans> <out-alifsms>"
}

show_help() {
    show_usage
    echo ""
    echo "Build the alignments graphs."
    echo ""
    echo "  --help -h       show this help message"
    echo "  --logdir        logging directory for the parallel environment (default: $logdir)"
    echo "  --njobs         number of parallel jobs (default: $njobs)"
}

. $SLAB_ROOT/tools/utils/parse_options.sh

if [ $# -ne 4 ]; then
    show_usage 1>&2
    exit 1
fi

hmms=$1 && assert_not_missing $scp
lexicon=$2 && assert_not_missing $config
trans=$3 && assert_not_missing $trans
out=$4

if [ -f $out ]; then
    echo "The alignment graphs are already built in $out."
    exit 0
fi

tmp=$(mktemp -d -p $(pwd))
trap 'rm -fr "$tmp"; trap - EXIT; exit' EXIT INT HUP
cwd=$(pwd)
cd $tmp
split -n l/$njobs $trans --numeric-suffixes=1
rename 's/x0+/x/' x*
cd $cwd

. $SLAB_ROOT/tools/monophone/parallel_env.sh
$parallel_cmd_alis julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/monophone/scripts/makealis.jl \
    $hmms \
    $lexicon \
    $tmp/x\$SGE_TASK_ID \
    $tmp/\$SGE_TASK_ID.jld2


julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/monophone/scripts/concatalis.jl \
    $out \
    $tmp/[1-9]*jld2

