#!/bin/sh -e

# SPDX-License-Identifier: MIT

cmd=$(basename $0)
. $SLAB_ROOT/tools/utils/utils.sh

start_sil=no
end_sil=no

show_usage() {
    echo "usage: $cmd [options] <hmms> <ploop>"
}

show_help() {
    show_usage
    echo ""
    echo "Make phone-loop decoding graph."
    echo ""
    echo "  -e              phone-loop ends with non-speech unit"
    echo "  -h              show this help message"
    echo "  -s              phone-loop starts with non-speech unit"
}

while :; do
    case "$1" in
        -e) end_sil=yes; shift;;
        -h) show_help; exit 0;;
        -s) start_sil=yes; shift;;
        -*)
            echo "Unknown option: $1. Try '$0 -h' for more informations."  1>&2
            echo "" 1>&2
            show_usage 1>&2
            exit 1;;
        *) break;;
    esac
    shift
done

if [ $# -ne 2 ]; then
    show_usage 1>&2
    exit 1
fi

hmms=$1 && assert_not_missing $hmms
ploop=$2

if [ -f $ploop ]; then
    echo "The phone-loop already exists in $ploop."
    exit 0
fi

[ $start_sil=yes ] && sopt="-s"
[ $end_sil=yes ] && eopt="-e"

julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/monophone/scripts/makephoneloop.jl \
    $sopt $eopt \
    $hmms \
    $ploop

