#!/bin/sh -e

. $SLAB_ROOT/tools/utils/utils.sh

show_usage() {
    echo "usage: $(basename $0) [options] [dataset]"
}

show_help() {
    show_usage
    echo ""
    echo "Show the possible type of features. If 'dataset' is provided, show "
    echo "the type of features already extracted for this dataset."
    echo ""
    echo "  -h              show this help message"
}

while :; do
    case "$1" in
        -h) show_help; exit 0;;
        -*)
            echo "unknown option: $1. Try '$0 -h' for more informations."  1>&2
            echo "" 1>&2
            show_usage 1>&2
            exit 1;;
        *) break;;
    esac
    shift
done

if [ $# -gt 1 ]; then
    show_usage 1>&2
    exit 1
fi

dataset=$1
if [ -z $dataset ]; then
    for file in $SLAB_ROOT/recipes/features/conf/*toml; do
        bname=$(basename $file)
        echo ${bname%%.*}
    done
elif [ -d $SLAB_FEATURES/$dataset ] && [ ! -z $(ls $SLAB_FEATURES/$dataset | grep h5) ]; then
    for file in $(ls $SLAB_FEATURES/$dataset | grep h5); do
        bname=$(basename $file)
        echo ${bname%%.*}
    done
else
    echo "No features extracted for $dataset."
fi

