#!/bin/sh -e

# SPDX-License-Identifier: MIT

cmd=$(basename $0)


#######################################################################
# Arguments

compression=0
njobs=1

#######################################################################

show_usage() {
    echo "usage: $cmd [options] <scp> <config> <out>"
}

show_help() {
    show_usage
    echo ""
    echo "Extract speech features from <scp> into a HDF5 archive."
    echo ""
    echo "  --compression   compression level from 0 to 9 (default: $compression)"
    echo "  --help -h       show this help message"
    echo "  --njobs         use N parallel jobs (default: $njobs)"
}

. parse_options.sh

if [ $# -ne 3 ]; then
    show_usage 1>&2
    exit 1
fi

scp=$1 && assert_not_missing $scp
config=$2 && assert_not_missing $config
out=$3
odir=$(dirname $out)
mkdir -p $odir

if [ -f $out ]; then
    echo "The features are already extracted ($out)."
    exit 0
fi

echo "Extracting features from $scp to $out."

tmp=$(mktemp -d -p $odir)
trap 'rm -fr "$tmp"; trap - EXIT; exit' EXIT INT HUP
cwd=$(pwd)
cd $tmp
split -n l/$njobs $scp --numeric-suffixes=1
rename 's/x0+/x/' x*
cd $cwd

. $SLAB_ROOT/tools/features/parallel_env.sh
$parallel_cmd julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/features/scripts/features.jl \
    -c $compression \
    $config \
    $tmp/x\$SGE_TASK_ID \
    $tmp/\$SGE_TASK_ID.h5

julia --project=$SLAB_ROOT/Project.toml \
    $SLAB_ROOT/tools/features/scripts/concat.jl \
    -c $compression \
    $out \
    $tmp/[1-9]*h5

