# SPDX-License-Identifier: MIT

include ../../Makefile.config

FEA_TYPE ?= mfcc_d_dd_16kHz
FEA_DIR ?= $(ROOT_FEA_DIR)/$(DATASET)/$(FEA_TYPE)
FEA_CONFIG ?= $(CONFIGS)/$(FEA_TYPE).toml
FEA_PARALLEL_NJOBS ?= 30
FEA_PARALLEL_ARGS ?= "-S /bin/bash"
